# Generated by Django 5.2.6 on 2025-10-13 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('present', 'Present')], default='absent', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user')},
        ),
    ]
